# Generated by Django 3.2.6 on 2021-09-10 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('PrimeiroNome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(max_length=50)),
                ('Telefone', models.CharField(default='(00)00000-0000', max_length=50)),
                ('Dor', models.BooleanField(default=False)),
                ('Problema', models.TextField(default='descreva o que sente')),
                ('horario', models.DateTimeField()),
            ],
        ),
    ]
