# Generated by Django 3.2.6 on 2021-09-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PrimeiroNome', models.CharField(max_length=50)),
                ('Sobrenome', models.CharField(max_length=50)),
                ('Telefone', models.DecimalField(decimal_places=11, default='(00)00000-0000', max_digits=11)),
                ('Dor', models.BooleanField(default=False)),
                ('Problema', models.TextField(default='descreva o que sente')),
            ],
        ),
    ]
