# Generated by Django 3.2.6 on 2021-09-05 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='Telefone',
            field=models.CharField(default='(00)00000-0000', max_length=50),
        ),
    ]
