# Generated by Django 3.2.6 on 2021-09-10 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(default=False, max_length=254),
        ),
    ]
