# Generated by Django 3.2.6 on 2021-09-10 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0002_agendamento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
