# Generated by Django 3.2.6 on 2021-09-10 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_alter_agendamento_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='Problema',
            field=models.TextField(default='descreva o problema'),
        ),
    ]
