# Generated by Django 3.2.6 on 2021-09-09 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0003_alter_agendamento_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='horario',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Agenda.agendamento')),
                ('hora', models.DateField()),
            ],
        ),
    ]
