# Generated by Django 3.2.6 on 2021-09-09 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_horario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='horario',
        ),
    ]
