# Generated by Django 3.2.6 on 2021-09-13 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0004_auto_20210913_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.CharField(max_length=50),
        ),
    ]
