# Generated by Django 3.2.6 on 2021-09-13 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Agenda', '0005_alter_agendamento_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='agendamento',
            name='horario',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
